### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by DEEPNESSD** [hkristof03/Homography#1]
请问有相关参考论文吗

**Comment by hkristof03** [comment]
I used Google translate and if it was right you are asking for references. The project was implemented based on university lecture and practice materials, which are not publicly available, unfortunately. The code should be understandable if you search for algorithm for Homography computation and RANSAC optimization.

**Comment by DEEPNESSD** [comment]
Thank you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月12日(星期二) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hkristof03/Homography] 您好 (Issue #1)





 
我使用谷歌翻译，如果它是正确的，你要求参考。不幸的是，该项目是根据大学讲座和实践材料实施的，这些材料不公开。如果您搜索用于 Homography 计算和 RANSAC 优化的算法，该代码应该是可以理解的。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。消息 ID：<hkristof03/Homography/issues/1/1096252756 @ github 。com&gt;

**Comment by DEEPNESSD** [comment]
Excuse me. I want to learn how to delete the wrong matching points of RANSAC in the direction of image recognition. I want to consider whether to optimize the RANSAC algorithm. Do you have relevant codes and papers for help? I will quote your article in the paper.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月12日(星期二) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hkristof03/Homography] 您好 (Issue #1)





 
我使用谷歌翻译，如果它是正确的，你要求参考。不幸的是，该项目是根据大学讲座和实践材料实施的，这些材料不公开。如果您搜索用于 Homography 计算和 RANSAC 优化的算法，该代码应该是可以理解的。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。消息 ID：<hkristof03/Homography/issues/1/1096252756 @ github 。com&gt;

**Comment by hkristof03** [comment]
Well I found these that I saved when I worked on this:

http://cg.elte.hu/~hajder/vision/ (university materials, looks like its public)
https://www.youtube.com/watch?v=MlaIWymLCD8
http://www.cs.otago.ac.nz/homepages/smartin/presentations/SMartin_Stability.pdf
https://www.youtube.com/watch?v=Cu1f6vpEilg
https://web.stanford.edu/class/cs231a/course_notes.html

Also, check out the relevant parts in the OpenCV tutorials, like feature matching with SURF + Homography.

Hope it helps.

**Comment by DEEPNESSD** [comment]
Thank you very much. I thought it was Chinese. i 'm sorry。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月12日(星期二) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hkristof03/Homography] 您好 (Issue #1)





 
好吧，我发现这些是我在处理此问题时保存的：
 
http://cg.elte.hu/~hajder/vision/（大学资料，貌似是公开的）
 https://www.youtube.com/watch?v=MlaIWymLCD8 
 http://www.cs.otago.ac .nz/homepages/smartin/presentations/SMartin_Stability.pdf 
 https://www.youtube.com/watch?v=Cu1f6vpEilg 
 https://web.stanford.edu/class/cs231a/course_notes.html
 
希望能帮助到你。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。消息 ID：<hkristof03/Homography/issues/1/1096275009 @ github 。com&gt;
